# ===============================
# APPLICATION INFO
# ===============================
spring.application.name=task-master
application.version=1.0.0

# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# ACTIVE PROFILE
# ===============================
spring.profiles.active=dev

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# JWT SECURITY
# ===============================
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-token.expiration=604800000

# ===============================
# LOGGING
# ===============================
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.sun.rmi=OFF
logging.level.javax.management=OFF
logging.level.com.zaxxer.hikari=INFO
logging.file.name=logs/app.log

# ===============================
# JMX (DISABLE TO PREVENT RMI NOISE)
# ===============================
spring.jmx.enabled=false

# ===============================
# EMAIL
# ===============================
spring.mail.host=smtp.example.com
spring.mail.port=587
spring.mail.username=default@example.com
spring.mail.password=defaultpassword
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# REDIS
# ===============================
spring.data.redis.host=localhost
spring.data.redis.port=6379
logging.level.io.lettuce.core=INFO
logging.level.org.springframework.data.redis=INFO

# Set logging levels to reduce debug noise
logging.level.org.apache.tomcat.util.net=INFO

management.endpoints.web.exposure.include=health,metrics,prometheus,info,threaddump,heapdump,db
management.endpoint.health.show-details=always
management.metrics.enable.process=true
management.metrics.enable.system=true
management.metrics.enable.logback=true
management.endpoints.web.base-path=/actuator

# Compression
server.compression.enabled=true
server.compression.min-response-size=1024

# Connection Pool
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Batch Processing
spring.jpa.properties.hibernate.jdbc.batch_size=20
spring.jpa.properties.hibernate.order_inserts=true
